BRAINS = {
    "nda_brain": [
        "https://www.sec.gov/edgar/search-and-access",
        "https://www.sec.gov/edgar/search/#/q=nda&filter_forms=10-K",
        "https://github.com/ContractStandards/Contract-Clauses",
        "https://onenda.org/",
        "https://huggingface.co/datasets/atticus-project/cuad",
        "https://github.com/jamesacampbell/contracts",
        "https://github.com/alangrafu/legal-docs",
        "https://www.dol.gov/agencies/oasam/site-closures/nda",
        "https://archive.org/search?query=non-disclosure+agreement",
    ],
    "msa_brain": [
        "https://www.sec.gov/edgar/search-and-access",
        "https://www.sec.gov/edgar/search/#/q=%22master%20service%20agreement%22",
        "https://nvca.org/model-legal-documents/",
        "https://www.techcontracts.com/resources/",
        "https://huggingface.co/datasets/lex_glue",
        "https://content.next.westlaw.com/practical-law",
        "https://www.miamidade.gov/Apps/ContractSearch/",
        "https://www.data.gov/search?q=contract",
        "https://sam.gov/content/opportunities",
        "https://archive.org/search?query=%22service+agreement%22",
    ],
    "investigation_brain": [
        "https://www.cs.cmu.edu/~enron/",
        "https://www.sec.gov/enforcement",
        "https://www.justice.gov/news",
        "https://www.courtlistener.com/",
        "https://www.oig.dol.gov/reports.htm",
        "https://www.ftc.gov/legal-library/browse/cases-proceedings",
        "https://www.govinfo.gov/app/collection/chrg",
        "https://openjustice.doj.ca.gov/",
        "https://vault.fbi.gov/",
        "https://www.nist.gov/publications",
    ],
    "case_intelligence_brain": [
        "https://www.courtlistener.com/api/bulk-data/",
        "https://www.recapthelaw.org/",
        "https://www.supremecourt.gov/opinions/opinions.aspx",
        "https://www.uscourts.gov/court-records",
        "https://www.govinfo.gov/app/collection/uscourts",
        "https://vault.fbi.gov/",
        "https://case.law/",
        "https://opendata.cityofnewyork.us/",
    ],
    "new_york_module": [
        "https://public.leginfo.state.ny.us/laws/",
        "https://www.nycourts.gov/courts/appeals/decisions/",
        "https://nycourts.gov/courts/ad1/Decisions.shtml",
        "https://ag.ny.gov/press-releases",
        "https://opendata.cityofnewyork.us/",
        "https://www.nysenate.gov/transparency/contracts",
        "https://www.nyc.gov/site/law/publications/publications.page",
        "https://www.nycourts.gov/courthelp/UGC/UCC.shtml",
        "https://wwe1.osc.state.ny.us/transparency/contracts/contractsearch.cfm",
    ],
}
